**Performing matrix multiplication and finding eigen vectors and eigen values using TensorFlow**

Computing the eigenvalues and right eigenvectors of a given square array using NumPy library.

In [ ]:
# importing numpy library
import numpy as np

# create numpy 2d-array
m = np.array([[0, 1],
			[-2, -3]])

print("Printing the Original square array:\n",m)
print()
print('***************************************')
print()
# finding eigenvalues and eigenvectors
w, v = np.linalg.eig(m)

# printing eigen values
print("Printing the Eigen values of the given square array:\n",w)
print()
# printing eigen vectors
print("Printing Right Eigen Vectors of the given square array:\n",v)


Printing the Original square array:
 [[ 0  1]
 [-2 -3]]

***************************************

Printing the Eigen values of the given square array:
 [-1. -2.]

Printing Right Eigen Vectors of the given square array:
 [[ 0.70710678 -0.4472136 ]
 [-0.70710678  0.89442719]]


In [ ]:
# importing numpy library
import numpy as np

# create numpy 2d-array
m = np.array([[1, 2, 3],
			[2, 3, 4],
			[4, 5, 6]])

print("Printing the Original square array:\n",m)
print()
print('***************************************')
print()

# finding eigenvalues and eigenvectors
w, v = np.linalg.eig(m)

# printing eigen values
print("Printing the Eigen values of the given square array:\n",w)
print()
# printing eigen vectors
print("Printing Right eigenvectors of the given square array:\n",v)


Printing the Original square array:
 [[1 2 3]
 [2 3 4]
 [4 5 6]]

***************************************

Printing the Eigen values of the given square array:
 [ 1.08309519e+01 -8.30951895e-01 -1.24701000e-16]

Printing Right eigenvectors of the given square array:
 [[ 0.34416959  0.72770285  0.40824829]
 [ 0.49532111  0.27580256 -0.81649658]
 [ 0.79762415 -0.62799801  0.40824829]]


Computing the eigenvalues and right eigenvectors of a given square array using Tensorflow.

In [ ]:
import tensorflow as tf

In [ ]:
# Let's see how we can compute the eigen vectors and values from a matrix

e_matrix_A = tf.random.uniform([2, 2], minval=3, maxval=10, dtype=tf.float32, name="matrixA")

print("Matrix A: \n{}\n\n".format(e_matrix_A))

Matrix A: 
[[9.116089 6.260758]
 [7.916345 8.771866]]




In [ ]:
# Calculating the eigen values and vectors using tf.linalg.eigh, if you only want the values you can use eigvalsh

eigen_values_A, eigen_vectors_A = tf.linalg.eigh(e_matrix_A)

print("Eigen Vectors: \n{} \n\nEigen Values: \n{}\n".format(eigen_vectors_A, eigen_values_A))

Eigen Vectors: 
[[-0.6993797   0.71475035]
 [ 0.71475035  0.6993797 ]] 

Eigen Values: 
[ 1.0257617 16.862194 ]



In [ ]:
# Let's see how we can compute the eigen vectors and values from a matrix

e_matrix_A = tf.random.uniform([3, 3], minval=3, maxval=10, dtype=tf.float32, name="matrixA")

print("Matrix A: \n{}\n\n".format(e_matrix_A))

Matrix A: 
[[7.5458817 4.3033495 5.2567573]
 [4.974057  3.6268468 9.713013 ]
 [5.0875545 3.1186485 6.895154 ]]




In [ ]:
# Calculating the eigen values and vectors using tf.linalg.eigh, if you only want the values you can use eigvalsh

eigen_values_A, eigen_vectors_A = tf.linalg.eigh(e_matrix_A)

print("Eigen Vectors: \n{} \n\nEigen Values: \n{}\n".format(eigen_vectors_A, eigen_values_A))

Eigen Vectors: 
[[ 0.59897846 -0.42632568  0.67784315]
 [-0.7963012  -0.40637407  0.44806755]
 [-0.08443513  0.80815005  0.582893  ]] 

Eigen Values: 
[ 0.21604107  2.6431053  15.208745  ]

